/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-11-26")
public class MtLRUSampleTResponse implements org.apache.thrift.TBase<MtLRUSampleTResponse, MtLRUSampleTResponse._Fields>, java.io.Serializable, Cloneable, Comparable<MtLRUSampleTResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MtLRUSampleTResponse");

  private static final org.apache.thrift.protocol.TField BLOCK_ID_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("BlockIdList", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MtLRUSampleTResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MtLRUSampleTResponseTupleSchemeFactory());
  }

  public List<BlockIdToCValue> BlockIdList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BLOCK_ID_LIST((short)1, "BlockIdList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BLOCK_ID_LIST
          return BLOCK_ID_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BLOCK_ID_LIST, new org.apache.thrift.meta_data.FieldMetaData("BlockIdList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BlockIdToCValue.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MtLRUSampleTResponse.class, metaDataMap);
  }

  public MtLRUSampleTResponse() {
  }

  public MtLRUSampleTResponse(
    List<BlockIdToCValue> BlockIdList)
  {
    this();
    this.BlockIdList = BlockIdList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MtLRUSampleTResponse(MtLRUSampleTResponse other) {
    if (other.isSetBlockIdList()) {
      List<BlockIdToCValue> __this__BlockIdList = new ArrayList<BlockIdToCValue>(other.BlockIdList.size());
      for (BlockIdToCValue other_element : other.BlockIdList) {
        __this__BlockIdList.add(new BlockIdToCValue(other_element));
      }
      this.BlockIdList = __this__BlockIdList;
    }
  }

  public MtLRUSampleTResponse deepCopy() {
    return new MtLRUSampleTResponse(this);
  }

  @Override
  public void clear() {
    this.BlockIdList = null;
  }

  public int getBlockIdListSize() {
    return (this.BlockIdList == null) ? 0 : this.BlockIdList.size();
  }

  public java.util.Iterator<BlockIdToCValue> getBlockIdListIterator() {
    return (this.BlockIdList == null) ? null : this.BlockIdList.iterator();
  }

  public void addToBlockIdList(BlockIdToCValue elem) {
    if (this.BlockIdList == null) {
      this.BlockIdList = new ArrayList<BlockIdToCValue>();
    }
    this.BlockIdList.add(elem);
  }

  public List<BlockIdToCValue> getBlockIdList() {
    return this.BlockIdList;
  }

  public MtLRUSampleTResponse setBlockIdList(List<BlockIdToCValue> BlockIdList) {
    this.BlockIdList = BlockIdList;
    return this;
  }

  public void unsetBlockIdList() {
    this.BlockIdList = null;
  }

  /** Returns true if field BlockIdList is set (has been assigned a value) and false otherwise */
  public boolean isSetBlockIdList() {
    return this.BlockIdList != null;
  }

  public void setBlockIdListIsSet(boolean value) {
    if (!value) {
      this.BlockIdList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BLOCK_ID_LIST:
      if (value == null) {
        unsetBlockIdList();
      } else {
        setBlockIdList((List<BlockIdToCValue>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BLOCK_ID_LIST:
      return getBlockIdList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BLOCK_ID_LIST:
      return isSetBlockIdList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MtLRUSampleTResponse)
      return this.equals((MtLRUSampleTResponse)that);
    return false;
  }

  public boolean equals(MtLRUSampleTResponse that) {
    if (that == null)
      return false;

    boolean this_present_BlockIdList = true && this.isSetBlockIdList();
    boolean that_present_BlockIdList = true && that.isSetBlockIdList();
    if (this_present_BlockIdList || that_present_BlockIdList) {
      if (!(this_present_BlockIdList && that_present_BlockIdList))
        return false;
      if (!this.BlockIdList.equals(that.BlockIdList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_BlockIdList = true && (isSetBlockIdList());
    list.add(present_BlockIdList);
    if (present_BlockIdList)
      list.add(BlockIdList);

    return list.hashCode();
  }

  @Override
  public int compareTo(MtLRUSampleTResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBlockIdList()).compareTo(other.isSetBlockIdList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBlockIdList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.BlockIdList, other.BlockIdList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MtLRUSampleTResponse(");
    boolean first = true;

    sb.append("BlockIdList:");
    if (this.BlockIdList == null) {
      sb.append("null");
    } else {
      sb.append(this.BlockIdList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MtLRUSampleTResponseStandardSchemeFactory implements SchemeFactory {
    public MtLRUSampleTResponseStandardScheme getScheme() {
      return new MtLRUSampleTResponseStandardScheme();
    }
  }

  private static class MtLRUSampleTResponseStandardScheme extends StandardScheme<MtLRUSampleTResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MtLRUSampleTResponse struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BLOCK_ID_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.BlockIdList = new ArrayList<BlockIdToCValue>(_list0.size);
                BlockIdToCValue _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new BlockIdToCValue();
                  _elem1.read(iprot);
                  struct.BlockIdList.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setBlockIdListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MtLRUSampleTResponse struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.BlockIdList != null) {
        oprot.writeFieldBegin(BLOCK_ID_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.BlockIdList.size()));
          for (BlockIdToCValue _iter3 : struct.BlockIdList)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MtLRUSampleTResponseTupleSchemeFactory implements SchemeFactory {
    public MtLRUSampleTResponseTupleScheme getScheme() {
      return new MtLRUSampleTResponseTupleScheme();
    }
  }

  private static class MtLRUSampleTResponseTupleScheme extends TupleScheme<MtLRUSampleTResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MtLRUSampleTResponse struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBlockIdList()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetBlockIdList()) {
        {
          oprot.writeI32(struct.BlockIdList.size());
          for (BlockIdToCValue _iter4 : struct.BlockIdList)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MtLRUSampleTResponse struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.BlockIdList = new ArrayList<BlockIdToCValue>(_list5.size);
          BlockIdToCValue _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new BlockIdToCValue();
            _elem6.read(iprot);
            struct.BlockIdList.add(_elem6);
          }
        }
        struct.setBlockIdListIsSet(true);
      }
    }
  }

}

