/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-11-26")
public class MtLRUBroadCricTOptions implements org.apache.thrift.TBase<MtLRUBroadCricTOptions, MtLRUBroadCricTOptions._Fields>, java.io.Serializable, Cloneable, Comparable<MtLRUBroadCricTOptions> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MtLRUBroadCricTOptions");

  private static final org.apache.thrift.protocol.TField CRIC_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("cricValue", org.apache.thrift.protocol.TType.I64, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MtLRUBroadCricTOptionsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MtLRUBroadCricTOptionsTupleSchemeFactory());
  }

  public long cricValue; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CRIC_VALUE((short)1, "cricValue");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CRIC_VALUE
          return CRIC_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CRICVALUE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CRIC_VALUE, new org.apache.thrift.meta_data.FieldMetaData("cricValue", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MtLRUBroadCricTOptions.class, metaDataMap);
  }

  public MtLRUBroadCricTOptions() {
  }

  public MtLRUBroadCricTOptions(
    long cricValue)
  {
    this();
    this.cricValue = cricValue;
    setCricValueIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MtLRUBroadCricTOptions(MtLRUBroadCricTOptions other) {
    __isset_bitfield = other.__isset_bitfield;
    this.cricValue = other.cricValue;
  }

  public MtLRUBroadCricTOptions deepCopy() {
    return new MtLRUBroadCricTOptions(this);
  }

  @Override
  public void clear() {
    setCricValueIsSet(false);
    this.cricValue = 0;
  }

  public long getCricValue() {
    return this.cricValue;
  }

  public MtLRUBroadCricTOptions setCricValue(long cricValue) {
    this.cricValue = cricValue;
    setCricValueIsSet(true);
    return this;
  }

  public void unsetCricValue() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CRICVALUE_ISSET_ID);
  }

  /** Returns true if field cricValue is set (has been assigned a value) and false otherwise */
  public boolean isSetCricValue() {
    return EncodingUtils.testBit(__isset_bitfield, __CRICVALUE_ISSET_ID);
  }

  public void setCricValueIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CRICVALUE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CRIC_VALUE:
      if (value == null) {
        unsetCricValue();
      } else {
        setCricValue((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CRIC_VALUE:
      return getCricValue();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CRIC_VALUE:
      return isSetCricValue();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MtLRUBroadCricTOptions)
      return this.equals((MtLRUBroadCricTOptions)that);
    return false;
  }

  public boolean equals(MtLRUBroadCricTOptions that) {
    if (that == null)
      return false;

    boolean this_present_cricValue = true;
    boolean that_present_cricValue = true;
    if (this_present_cricValue || that_present_cricValue) {
      if (!(this_present_cricValue && that_present_cricValue))
        return false;
      if (this.cricValue != that.cricValue)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_cricValue = true;
    list.add(present_cricValue);
    if (present_cricValue)
      list.add(cricValue);

    return list.hashCode();
  }

  @Override
  public int compareTo(MtLRUBroadCricTOptions other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCricValue()).compareTo(other.isSetCricValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCricValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cricValue, other.cricValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MtLRUBroadCricTOptions(");
    boolean first = true;

    sb.append("cricValue:");
    sb.append(this.cricValue);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MtLRUBroadCricTOptionsStandardSchemeFactory implements SchemeFactory {
    public MtLRUBroadCricTOptionsStandardScheme getScheme() {
      return new MtLRUBroadCricTOptionsStandardScheme();
    }
  }

  private static class MtLRUBroadCricTOptionsStandardScheme extends StandardScheme<MtLRUBroadCricTOptions> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MtLRUBroadCricTOptions struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CRIC_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.cricValue = iprot.readI64();
              struct.setCricValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MtLRUBroadCricTOptions struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CRIC_VALUE_FIELD_DESC);
      oprot.writeI64(struct.cricValue);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MtLRUBroadCricTOptionsTupleSchemeFactory implements SchemeFactory {
    public MtLRUBroadCricTOptionsTupleScheme getScheme() {
      return new MtLRUBroadCricTOptionsTupleScheme();
    }
  }

  private static class MtLRUBroadCricTOptionsTupleScheme extends TupleScheme<MtLRUBroadCricTOptions> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MtLRUBroadCricTOptions struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCricValue()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetCricValue()) {
        oprot.writeI64(struct.cricValue);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MtLRUBroadCricTOptions struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.cricValue = iprot.readI64();
        struct.setCricValueIsSet(true);
      }
    }
  }

}

